import argparse
import json
from pathlib import Path

from datasets import Dataset
from ragas import evaluate
from ragas.metrics import answer_relevancy, context_precision, faithfulness


def load_traces(trace_path: Path, limit: int | None = None) -> list[dict]:
    rows = []
    with trace_path.open("r", encoding="utf-8") as file:
        for line in file:
            line = line.strip()
            if not line:
                continue
            raw = json.loads(line)
            contexts = raw.get("contexts", [])
            reference = raw.get("reference")
            row = {
                "trace_id": raw.get("trace_id"),
                "user_input": raw.get("query", ""),
                "question": raw.get("query", ""),
                "response": raw.get("answer", ""),
                "answer": raw.get("answer", ""),
                "retrieved_contexts": contexts,
                "contexts": contexts,
            }
            if reference:
                row["reference"] = reference
                row["ground_truth"] = reference
            rows.append(row)
            if limit is not None and len(rows) >= limit:
                break
    return rows


def build_metrics(rows: list[dict]):
    metrics = [faithfulness, answer_relevancy]
    if rows and all(row.get("reference") for row in rows):
        metrics.append(context_precision)
    return metrics


def main():
    parser = argparse.ArgumentParser(description="Run ragas over logged RAG traces.")
    parser.add_argument(
        "--trace-path",
        default="/app/evaluation_logs/rag_traces.jsonl",
        help="Path to the JSONL trace log generated by the backend.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional maximum number of traces to evaluate.",
    )
    args = parser.parse_args()

    trace_path = Path(args.trace_path)
    if not trace_path.exists():
        raise FileNotFoundError(f"Trace log not found: {trace_path}")

    rows = load_traces(trace_path, limit=args.limit)
    if not rows:
        raise ValueError(f"No traces available in {trace_path}")

    dataset = Dataset.from_list(rows)
    metrics = build_metrics(rows)
    results = evaluate(dataset=dataset, metrics=metrics)

    print(json.dumps(results.to_pandas().to_dict(orient="records"), indent=2))


if __name__ == "__main__":
    main()
